-- REQUIRES MYSQL-SERVER-5.7.6 OR HIGHER

CREATE DATABASE IF NOT EXISTS TELEPHONE_DIRECTORY;

USE TELEPHONE_DIRECTORY;

CREATE USER IF NOT EXISTS 'DIRECTORY_APP'@'localhost' IDENTIFIED BY 'D!rect0ry';
